apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-cluster
spec:
  replicas: 5
  selector:
    matchLabels:
      app: akka-simple-cluster
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: akka-simple-cluster
    spec:
      serviceAccountName: akka-simple-cluster
      containers:
      - image: softwaremill/akka-simple-cluster-k8s:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: akka-simple-cluster
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        ports:
        # akka remoting
        - name: remoting
          containerPort: 2551
        # akka-management api
        - name: api
          containerPort: 8080
        # akka-management bootstrap
        - name: management
          containerPort: 8558
        # health
        livenessProbe:
          httpGet:
            path: /alive
            port: management
        readinessProbe:
          httpGet:
            path: /ready
            port: management

